#!/bin/bash

source /infra/utils

set -e
set -u
set -x
set -o pipefail

pip3 install reportlab markdown
rm -rf $OMERO_DIST/lib/scripts/omero

cd $TARGET
cd src/omero_figure/scripts
cp -r omero $OMERO_DIST/lib/scripts/

su - omero-server <<EOF
/opt/omero/server/venv3/bin/omero login -w omero root@omero
/opt/omero/server/venv3/bin/omero script list
EOF
