#!/bin/bash

set -e
set -u
set -x

/opt/omero/server/venv3/bin/pip install reportlab
/opt/omero/server/venv3/bin/pip install markdown
rm -rf $OMERO_DIST/lib/scripts/omero

cd $TARGET
cd omero_figure/scripts
cp -r omero $OMERO_DIST/lib/scripts/

export ICE_CONFIG=${OMERO_DIST}/etc/ice.config
export ROOTPASS=$(cat $ICE_CONFIG | grep omero.rootpass | cut -f2 -d=)
export PATH=$PATH:$OMERO_DIST/bin
omero login -w $ROOTPASS root@omero
omero script list
