#!/bin/bash

source /infra/utils

set -e
set -u
set -x
set -o pipefail

pip3 install reportlab markdown
rm -rf $OMERO_DIST/lib/scripts/omero

cd $TARGET
mkdir -p $OMERO_DIST/lib/scripts/omero/figure_scripts/
cp figure/ome_figure/Figure_To_Pdf.py $OMERO_DIST/lib/scripts/omero/figure_scripts/Figure_To_Pdf.py

su - omero-server <<EOF
/opt/omero/server/venv3/bin/omero login -w omero root@omero
/opt/omero/server/venv3/bin/omero script list
EOF
